SOONEST_RETRY_AFTER_NO_SPECULATE = 2
# SOONEST_RETRY_AFTER_SPECULATE=15
SOONEST_RETRY_AFTER_SPECULATE = 1
DEFAULT_SPECULATIVECAP_TOTAL_TASKS = 0.1
DEFAULT_SPECULATIVE_MAXIMUM_ALLOWED_TASKS = 10

# Task possible states
NUM_TASK_STATES = 6
ON_SCHEDULE = -NUM_TASK_STATES
ALREADY_SPECULATING = ON_SCHEDULE + 1
TOO_NEW = NUM_TASK_STATES + 2
PROGRESS_IS_GOOD = NUM_TASK_STATES + 3
NOT_RUNNING = NUM_TASK_STATES + 4
TOO_LATE_TO_SPECULATE = NUM_TASK_STATES + 5

# Attempt states
NUM_ATTEMPT_STATES = 3
ATTEMPT_RUNNING = -NUM_ATTEMPT_STATES
ATTEMPT_STARTING = -NUM_ATTEMPT_STATES + 1
ATTEMPT_FINISHED = -NUM_ATTEMPT_STATES + 2

# Path in IBM COS for each task's arguments' pickle
DEFAULT_ARGUMENT_PATH = "_arguments"


MAX_BACKUP_FUNCTION_NUMBER = 2
BACKUP_INFO_KEY = "backup_task"
BACKUP_INFO_PATH = "tmp"
FUTURE_PREFIX= "futures"
COMMUNICATION_PREFIX= "task_info"
BASEPATH_PREFIX="monitor_tmp"
END_PREFIX="end"
START_PREFIX="start"
MONITOR_INFO_PATH="monitor_info"
DEFAULT_OUTPUT_PREFIX = "out"
SHUFFLE_OUTPUT_PREFIX ="shuffle_paths"

# Seconds before function execution time limit
TIMEOUT_MARGIN = 50

MAX_WAITING_TIME_HEARTBEAT = 9


RUNTIME_MAX_VALUE = 600
# factor used to calculate confidence interval within 95%.
DEFAULT_CI_FACTOR = 1.96
SPECULATIVE_SLOWTASK_THRESHOLD=10
MINIMUM_REGISTERED_PROPORTION_TO_SPECULATE = 0.2
LAST_TASK_PROPORTION_THRESHOLD_RUNTIME = 0.15
SPECULATION_REFERENCE_QUANTILE = 0.2
# SPECULATION_PROPORTION_REFERENCE= 0.6
SPECULATION_PROPORTION_REFERENCE= 1
MINIMUM_PROCESSED_FUNCTIONS_TO_SPECULATE = 0.2
MINIMUM_NUMBER_FUNCTIONS_TO_SPECULATE = 7
SPECULATION_START_TIME=15

NUM_POSSIBLE_MONITOR_ENDS=8
MONITOR_FINISH_NOT_ENOUGH_FUNCTION_NUMBER = -NUM_POSSIBLE_MONITOR_ENDS+0
MONITOR_FINISH_NOT_ENOUGH_FUNCTION_PROPORTION = -NUM_POSSIBLE_MONITOR_ENDS+1
MONITOR_FINISH_TIMEOUT = -NUM_POSSIBLE_MONITOR_ENDS+2
MONITOR_FINISH_MAXIMUM_SPECULATIVE_TASKS = -NUM_POSSIBLE_MONITOR_ENDS+3
MONITOR_FINISH_MAXIMUM_SPECULATIVE_TASK_PROPORTION = -NUM_POSSIBLE_MONITOR_ENDS+4
MONITOR_FINISH_ALL_TASKS_FINISHED = -NUM_POSSIBLE_MONITOR_ENDS+5
MONITOR_FINISH_MAXIMUM_RECURSION = -NUM_POSSIBLE_MONITOR_ENDS+6
MONITOR_FINISH_SIGNALED_FROM_CLIENT = -NUM_POSSIBLE_MONITOR_ENDS+7


MONITOR_TIMEOUT = 40