pywren: 
    storage_bucket: <BUCKET_NAME>
    #storage_backend: ibm_cos
    #compute_backend: ibm_cf
    #rabbitmq_monitor: <True/False>
    #remote_invoker: <True/False>
    #data_cleaner: <True/False>
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600000
    #runtime_memory: 256
    #workers: <MAX_NUM_OF_WORKERS>

#ibm:
   #iam_api_key: <IAM KEY>

ibm_cf:
    endpoint    : <REGION_ENDPOINT>
    namespace   : <NAMESPACE>
    api_key     : <API_KEY>
    #namespace_id : <NAMESPACE_ID> # Only for IAM auth

ibm_cos:
    endpoint    : <REGION_ENDPOINT>
    api_key     : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional

#rabbitmq:
    #amqp_url   : <RABBIT_AMQP_URL>  # amqp://

#knative:
   #endpoint    : <ISTIO_INGRESS_ENDPOINT>
   #docker_user : <DOCKER_HUB_USERNAME>
   #docker_token: <DOCKER_HUB_TOKEN>

#openwhisk:
    #endpoint    : <OW_ENDPOINT>
    #namespace   : <NAMESPACE>
    #api_key     : <AUTH_KEY>
    #insecure    : <True/False>

#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>

#infinispan:
    #username   : <USER_NAME>
    #password   : <PASSWORD>
    #endpoint   : <INFINISPAN_SERVER_URL:PORT>
